export const strings: any = JSON.parse(`{
  "lt": {
    "beginHeader": "Demonstracinė testavimo vieta",
    "category": "Kategorija",
    "testLang": "Testo kalba",
    "startExam": "Pradėkite egzaminą",
    "test": "Testas",
    "bCategory": "B kategorija",
    "taskNum": "iš 30 klausimas",
    "previousTask": "Ankstesnis klausimas",
    "nextTask": "Kitas klausimas",
    "timeLeft": "Laiko liko",
    "finishTest": "Užbaigti testą",
    "warningUnanswered": "Dėmesio! Yra neatsakytų klausimų. Jie automatiškai bus pažymėti kaip neteisingai atsakyti klausimai. Ar norite baigti testą?",
    "ok": "Gerai",
    "cancel": "Atsisakyti",
    "confirmFinish": "Ar norite baigti testą?",
    "langCode": "LT",
    "examRegistrationNumber": "Prašymo numeris",
    "examFail": "Egzaminas neišlaikytas",
    "examPass": "Egzaminas išlaikytas",
    "participant": "Dalyvis",
    "givenAnswers": "Pateikta užduočių",
    "correctAnswers": "Teisingų atsakymų",
    "incorrectAnswers": "Neteisingų atsakymų",
    "allowedErrors": "Leistinas klaidų kiekis",
    "viewAnswers": "Peržiūrėti atsakymus",
    "noIllustration": "Iliustracijos nėra",
    "close": "Uždaryti",
    "errorStart": "Negalima buvo pradėti egzamino.",
    "errorEnd": "Negalima buvo užbaigti egzamino.",
    "wait": "Palaukite..."
  },
  "en": {
    "beginHeader": "Demonstrational test place",
    "category": "Category:",
    "testLang": "Test language:",
    "startExam": "Start exam",
    "test": "Test:",
    "bCategory": "B category;",
    "taskNum": "of 30 Task",
    "previousTask": "Previous task",
    "nextTask": "Next task",
    "timeLeft": "Time left:",
    "finishTest": "Finish test",
    "warningUnanswered": "Warning! You have unanswered tasks. All unanswered tasks will be marked as incorrect. Are you sure you want to finish this test?",
    "ok": "OK",
    "cancel": "Cancel",
    "confirmFinish": "Are you sure you want to finish this test?",
    "langCode": "EN",
    "examRegistrationNumber": "Request number:",
    "examFail": "Failed",
    "examPass": "Passed",
    "participant": "Participant:",
    "givenAnswers": "Total tasks:",
    "correctAnswers": "Correct answers:",
    "incorrectAnswers": "Incorrect answers:",
    "allowedErrors": "Max wrong answers:",
    "viewAnswers": "Show test answers",
    "noIllustration": "No illustration",
    "close": "Close",
    "errorStart": "Couldn't start the exam.",
    "errorEnd": "Couldn't end the exam.",
    "wait": "Please wait..."
  }
}`);
